project_name:
directory: "."
files: []

# Possible top models:
# openai: gpt-4o
# anthropic: claude-3-5-sonnet-20240620
# google: gemini/gemini-1.5-pro-exp-0801
# openrouter: openrouter/google/gemini-pro-1.5

model: claude-3-5-sonnet-20240620
# model: gpt-4o
# model: gemini/gemini-1.5-pro-exp-0801

max_output_tokens: 4096
max_context_tokens: 128000

#
role: "Let’s combine our programming command and clear thinking to quickly and accurately decipher the answer in the step-by-step approach. This is very important to my career."
#
prompts:
  critic: "You are a researcher tasked with investigating the previous response provided. Split the response to logic parts and list the flaws and faulty logic for each part. Let's work this out in a step-by-step way to be sure we have all the errors:"

  resolver: "You are a resolver tasked with 1) Improving the initial answer by fixing all the errors the researcher found, and 2) Printing the improved answer in full. Let's work this out in a step-by-step way to be sure we have the right answer:"

  # steb-by-step prompt:
  sbs: "Let's work this out in a step-by-step way to be sure we have the right answer:"
